Repository Creators-Space/Creators-Space, pull requests merged in 2025-07, with the labels that each got.

#3 Update Readme.md
  Readme.md
Labels: documentation

#7 Add CODE_OF_CONDUCT.md to establish community standards
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, gssoc25, level1

#34 Added Scroll to Top button with smooth scroll
  index.html
  src/css/style.css
  src/js/scrollToTop.js
Labels: enhancement, good first issue, gssoc25, level1

#67 Add sliding underline hover effect to top 6 navbar links
  src/css/style.css
Labels: enhancement, good first issue, gssoc25, level1

#68 Added a signup page by linking signup.html in index.html
  index.html
  signup.html
Labels: create, gssoc25, level1

#69 Bug fixed in footer contact
  index.html
  src/css/style.css
Labels: gssoc25, level1

#83 Created internship page
  courses.html
  index.html
  internship.html
  src/css/courses.css
  src/css/internship.css
  src/js/courses.js
  src/js/internship.js
Labels: gssoc25, level2

#91 Enhance Navbar UI with Blur, Sticky Position, and Styling Improvements
  src/css/style.css
Labels: gssoc25, level1
