Repository Creators-Space/Creators-Space, pull requests merged in 2025-09, with the labels that each got.

#307 Added Contact Us Page
  CONTACT_FEATURE_DOCS.md
  about.html
  apply.html
  blog.html
  campus-ambassador.html
  contact.html
  courses.html
  enroll.html
  index.html
  internship.html
  projects.html
  services.html
  src/css/contact.css
  src/js/contact.js
Labels: gssoc25, level2, assigned

#313 Roadmaps Page
  about.html
  apply.html
  blog.html
  bookmarked.html
  campus-ambassador.html
  certificate/index.html
  courses.html
  enroll.html
  index.html
  internship.html
  projects.html
  roadmap.html
  services.html
  src/css/about.css
  src/css/blog.css
  src/css/bookmarked.css
  src/css/campus-ambassador.css
  src/css/certificates.css
  src/css/courses.css
  src/css/enroll.css
  src/css/internship.css
  src/css/newsletter.css
  src/css/profile.css
  src/css/projects.css
  src/css/roadmap.css
  src/css/services.css
  src/css/style.css
  src/js/roadmap.js
Labels: gssoc25, level3, assigned

#331 Fixed Overlapping More Info Text and Disappearing Image in Course Cards
  courses.html
  src/css/courses.css
Labels: gssoc25, level1, assigned

#334 Add password checklist to signup form
  signup.html
Labels: gssoc25, level2, assigned

#335 Add Navbar in Freelancing Page
  freelancing.html
Labels: gssoc25, level1, assigned

#336 Implemented selection of multiple techstack tags in filtering the projects - issue #324
  src/js/projects.js
Labels: gssoc25, level2, assigned

#339 Consistent Back To Top Button
  about.html
  projects.html
  src/css/about.css
Labels: gssoc25, level2, assigned

#348 Enhanced Text Color & Weight
  src/css/campus-ambassador.css
Labels: gssoc25, level1, assigned

#361 Contrast colours
  projects.html
Labels: gssoc25, level1, assigned

#367 Search bar UI misaligned on Internship page
  internship.html
  src/css/internship.css
Labels: gssoc25, level1, assigned

#369 Removed the extra projects option in resources
  campus-ambassador.html
Labels: duplicate, gssoc25, level1, assigned

#371 Removed unwanted text on nav bar
  internship.html
Labels: gssoc25, level1, assigned

#372 Fixed fonts and styles for readibility
  about.html
  src/css/about.css
  src/css/utils.css
Labels: gssoc25, level2, assigned

#377 New features added in Campus Ambessdor
  assets/aminations/why.gif
  campus-ambassador.html
  src/css/campus-ambassador.css
Labels: gssoc25, level2, assigned

#379 fix(forms): add placeholders and labels for usability and accessibility
  about.html
  blog.html
  bookmarked.html
  campus-ambassador.html
  certificate/index.html
  contact.html
  courses.html
  index.html
  internship.html
  login.html
  projects.html
  services.html
  signup.html
  src/css/style.css
Labels: enhancement, gssoc25, level2, assigned

#394 Fix: Updated CTA links in Services page to correct external resources
  services.html
  src/data/services.json
Labels: gssoc25, level2

#381 Feat/course card descriptions
  courses.html
  package-lock.json
  style.css
Labels: gssoc25, level1, assigned

#392 Issue #373 fixed
  blog.html
  projects.html
Labels: gssoc25, level2, assigned

#408 Enhance Dark Mode UI Elements
  index.html
  src/css/style.css
  src/js/language.js
Labels: gssoc25, level2, assigned

#416 Issue #373 fixed
  projects.html
Labels: gssoc25, level1, assigned

#417 Issue #393 fixed
  blog.html
  projects.html
Labels: gssoc25, level1, assigned

#419 [BUG FIX] Fixed dark mode on blog page.
  src/css/blog.css
Labels: bug, gssoc25, level1, assigned

#421 style: fix title alignment and card design on Bookmarked Courses page
  bookmarked.html
Labels: gssoc25, level1, assigned

#434 [BUG FIX] Styled dropdown menu for navbar elements on home page.
  src/css/style.css
Labels: enhancement, gssoc25, level1, assigned

#443 Added dark mode styles in Campus Ambassador Page
  campus-ambassador.html
  src/css/campus-ambassador.css
  src/css/style.css
Labels: gssoc25, level2, assigned
