Repository Creators-Space/Creators-Space, pull requests merged in 2025-08, with the labels that each got.

#110 Added bookmarked feature
  bookmarked.html
  courses.html
  index.html
  src/css/bookmarked.css
  src/css/courses.css
  src/css/style.css
  src/js/bookmarked.js
  src/js/coursebm.js
Labels: gssoc25, level2

#117 Fix placeholder social links in footer
  index.html
Labels: gssoc25, level1

#127 Apply dark theme support to all pages
  courses.html
  src/css/courses.css
  src/css/style.css
Labels: gssoc25, level2

#129 fixed no validation and user feedback on signup issue
  signup.html
  src/js/formValidation.js
Labels: gssoc25, level2

#139 Feature: Dynamic Internship Card Loader with JSON
  assets/images/blogpage/ui-ux.jpeg
  blog.html
  internship.html
  src/data/internship.json
Labels: gssoc25, level3

#135 fix: update navbar logo for dark/light mode
  assets/images/blogpage/uiux.jpeg
  assets/images/logo-nav-dark.png
  assets/images/logo-nav-light.png
  blog.html
  courses.html
  index.html
  internship.html
  src/js/navbar.js
  src/js/utils.js
Labels: gssoc25, level2, assigned

#189 FIX : Added the Back to Homepage button in the login and signup page
  login.html
  signup.html
Labels: gssoc25, level1, assigned

#194 added UI enhancement in back to top and add about html file
  about.html
  index.html
  src/css/about.css
  src/css/style.css
  src/js/about.js
  src/js/scrollToTop.js
Labels: gssoc25, level1, assigned

#198 Added complete About Us page with layout, styling and dark mode support
  about.html
  assets/images/aboutpage/mission.gif
  assets/images/aboutpage/vision.webp
  blog.html
  courses.html
  index.html
  internship.html
  src/css/about.css
Labels: gssoc25, level2, assigned

#199 Add apply now and enroll now functionality
  apply.html
  enroll.html
  index.html
  internship.html
Labels: gssoc25, level2, assigned

#203 feat: add course search filter and improve bookmarking
  courses.html
  src/css/courses.css
Labels: gssoc25, level2, assigned

#205 Reopen: Implement Google Sign-in using Firebase
  login.html
  src/js/firebase.js
Labels: gssoc25, level3, assigned

#206 Added Data Analyst course section with pricing and icon
  Screenshots/data-research.png
  index.html
Labels: gssoc25, level1, assigned

#209 Add Newsletter Subscription Popup Feature
  about.html
  index.html
  newsletter-demo.html
  src/css/newsletter.css
  src/css/style.css
  src/js/newsletter.js
  src/js/utils.js
Labels: gssoc25, level2, assigned

#233 Added Certificate Generation/Verification Module
  assets/aminations/loading.webp
  assets/images/Certificate/Creators-Sapce-Certificate Template.png
  certificate/index.html
  index.html
  src/css/certificates.css
  src/css/responsive.css
  src/css/style.css
  src/css/utils.css
Labels: documentation, enhancement, create, assigned, certificates

#263 Add Firebase Config to README
  Readme.md
Labels: gssoc25, level1, assigned

#268 Fixed the Spacing and Shadow
  login.html
Labels: gssoc25, level1, assigned

#274 📝 Updated README.md with Enhanced Documentation
  Readme.md
  Screenshots/bookmarks.png
  Screenshots/course.png
  Screenshots/homepage-dark.png
  Screenshots/homepage-light.png
  Screenshots/internship.png
  Screenshots/intro(dark).png
  Screenshots/intro(light).png
  Screenshots/login.png
  Screenshots/opensource.png
  Screenshots/services.png
  Screenshots/signup.png
Labels: gssoc25, level1, assigned

#275 Fixed navbar on Login and Signup Page
  login.html
  signup.html
Labels: gssoc25, level1, assigned

#277 Fixed issue #button: fix button bg in darkmode (in about us page)
  src/css/about.css
Labels: good first issue, gssoc25, level1, assigned

#292 Enhance UI of enroll page button of course and added description to the courses
  assets/images/illustrationimg.webp
  courses.html
  enroll.html
  src/css/courses.css
  src/css/enroll.css
Labels: gssoc25, level2, assigned

#299 issue #279 navbar dropdown ui
  src/css/style.css
Labels: gssoc25, level2, assigned
